// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVSvJfIj9AaSERReT70ufThr7Ip1_c-ZI',
    appId: '1:25543256610:web:dbd6fa00ca15d970c0f87b',
    messagingSenderId: '25543256610',
    projectId: 'lost-and-found-94aaf',
    authDomain: 'lost-and-found-94aaf.firebaseapp.com',
    storageBucket: 'lost-and-found-94aaf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwJMa8uJ7HFG1P8pUoSRwOTzn1hYro8UM',
    appId: '1:25543256610:android:2a11b912ce2cabe5c0f87b',
    messagingSenderId: '25543256610',
    projectId: 'lost-and-found-94aaf',
    storageBucket: 'lost-and-found-94aaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXrMHJG9CCX2pw5caGIzbMNvXDLM0bHEw',
    appId: '1:25543256610:ios:1bb5981f66985cc5c0f87b',
    messagingSenderId: '25543256610',
    projectId: 'lost-and-found-94aaf',
    storageBucket: 'lost-and-found-94aaf.firebasestorage.app',
    iosBundleId: 'com.gdg.lostAndFound',
  );
}
